config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :requests

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  get 'home/index'

end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :title, :description, :department, :date, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    @requests = Request.all
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      redirect_to @request
    else
      render 'new'
    end
  end

  def edit
    @request = Request.find(params[:id])
  end

  def show
    @request = Request.find(params[:id])
  end

  private
    def request_params
      params.require(:request).permit(:description, :title, :date, :department)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_navigation.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'A/B Testing', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link</a></li>-->

        <li><%= link_to 'New Request', new_request_path %></li>
        <li><%= link_to 'Active Tests', requests_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestingRequests</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
<% else %>
    <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
<% end %>
 <%= render "layouts/navigation" %>

 <div class="container">

  <%= yield %>

 </div>
</body>
</html>

app/views/requests/edit.html.erb
<h1>Edit Your Request</h1>

<%= form_for :request, url: requests_path(@article), method: :patch do |f| %>

    <% if @request.errors.any? %>
        <div id="request-submit-errors">
          <ul>
            <% @request.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.label :department %>
    <%= f.text_field :department %>
    <br>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br>
    <%= f.label :date %>
    <%= f.text_field :date %>
    <br>
    <%= f.submit "Submit Request" %>

<% end %>

app/views/requests/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Current Requests</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <h3>Department</h3>
  </div>
  <div class="col-md-3">
    <h3>Title</h3>
  </div>
  <div class="col-md-3">
    <h3>Description</h3>
  </div>
  <div class="col-md-3">
    <h3>Date</h3>
  </div>
</div>
<% @requests.each do |request| %>
    <div class="row">
      <div class="col-md-3">
        <h4><%= request.department %></h4>
      </div>
      <div class="col-md-3">
        <h4><%= request.title %></h4>
      </div>
      <div class="col-md-3">
        <h4><%= request.description %></h4>
      </div>
      <div class="col-md-3">
        <h4><%= request.date %></h4>
      </div>
    </div>
<% end %>

app/views/requests/new.html.erb
<%= form_for :request, url: requests_path do |f| %>

    <% if @request.errors.any? %>
      <div id="request-submit-errors" class="col-md-offset-4 col-md-4">
        <ul>
          <% @request.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

 <div class="row">

   <div class="col-md-4 col-md-offset-4">
     <h1>Request a Test</h1>
   </div>
   <div class="col-md-4 col-md-offset-4">
     <div class="row">
       <div class="col-md-4">
         <%= f.label :department %>
       </div>
       <div class="col-md-8">
         <%= f.text_field :department %>
       </div>
     </div>
   </div>
   <div class="col-md-4 col-md-offset-4">
     <div class="row">
       <div class="col-md-4">
         <%= f.label :title %>
       </div>
       <div class="col-md-8">
         <%= f.text_field :title %>
       </div>
     </div>
   </div>
   <div class="col-md-4 col-md-offset-4">
     <div class="row">
       <div class="col-md-4">
         <%= f.label :description %>
       </div>
       <div class="col-md-8">
         <%= f.text_area :description %>
       </div>
     </div>
   </div>
   <div class="col-md-4 col-md-offset-4">
     <div class="row">
       <div class="col-md-4">
         <%= f.label :date %>
       </div>
       <div class="col-md-8">
         <%= f.text_field :date %>
       </div>
     </div>
   </div>
   <div class="col-md-4 col-md-offset-4">
     <%= f.submit "Submit Request" %>
   </div>
 </div>

<% end %>

app/views/requests/show.html.erb
<p>
  <strong>Department:</strong>
  <%= @request.department %>
</p>

<p>
  <strong>Title:</strong>
  <%= @request.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @request.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @request.date %>
</p>